### ISSUE TITLE
Could you make the remove() method public?

### ISSUE THREAD

**Issue by MalcolmMcFly** [florent37/ViewTooltip#7]
This would be helpful for instances where when a user presses back `onKeyDown()` and you would like to remove ViewTooltip from the screen. i.e. Fragments, ViewPager

**Comment by florent37** [comment]
done, check the 1.0.4 ;)

**Comment by MalcolmMcFly** [comment]
Actually, remove() is still not accessible on the ViewTooltip object. It might take a little more work than I originally thought than just setting remove() to public.

**Comment by florent37** [comment]
the .show() could return the "view" object, so it will be possib le to save it into a variable, then cann .remove() on it later ?

**Comment by florent37** [comment]
can you try ? (it's in the 1.0.4)

**Comment by MalcolmMcFly** [comment]
I'm sorry, could you post an example of the flow you are suggesting.
